name: Request maintainer reviews

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      # Only run when package files are modified
      - '!var/spack/repos/builtin/packages/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Add reviewers
      run: |
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH") \
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/pulls/$pull_number/requested_reviewers \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "reviewers": ["adamjstewart"]
          }'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
